spring:
  application:
    name: edugestor

  datasource:
    url: "jdbc:postgresql://localhost:5432/edugestor"
    username: postgres
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: "12345678901234567890123456789012"
    expiration-ms: 3600000   # 1 hora em ms